id: PB82BC254
initial_creation_type: input
source_metadata:
  title: Wealth and Prosperity Series
  language: bo
  description: 'A selection of texts on the theme of wealth and prosperity including
    rites for summoning the spirit of prosperity or abundance (g.yang ''gugs):'
  volume:
    af80d4121391490da62c5979b240cbc8:
      title: Sang Offering to Yellow Jambhala
      parent: Offering
    07e8acf4bddd4d67b183721ec46c73e5:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Offering
    68b34fcff58d4211bf2a2586df0b737f:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Summoning Prosperity
    0127f2e709824a19849bea08c53fa30e:
      title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
      parent: Summoning Prosperity
    90bd6a694f114309adb7b859dbb0aae9:
      title: Summoning Prosperity
      parent: Summoning Prosperity
    73d5ae0a7ff048ada503b5150ef68963:
      title: A Brief Prayer for Summoning Prosperity
      parent: Summoning Prosperity
    fa115e341cde4402ae155cf31905b229:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Summoning Prosperity
    049659e3727f464281f3dc17c4ec0b2c:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
created_at: '2022-03-01T06:34:53.427376'
last_modified_at: '2022-03-01T06:34:53.427379'
statistics:
  total_words: 3265
  total_non_words: 319
quality:
  non_words_ratio: 0.1
